unstable_features = true
tab_spaces = 4
hard_tabs = true
use_field_init_shorthand = true
fn_single_line = true
imports_granularity = "Module"
normalize_comments = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
use_try_shorthand = true
